import type { PdfmeFieldMapping } from '@/types/skill';

/**
 * Coordinate mappings for the Victorian Contract of Sale of Land.
 * Measured from the standard REIV form (A4 pages, 210mm x 297mm).
 * All positions are in mm from the top-left corner of the page.
 * Pages are 0-indexed.
 *
 * Page layout (from the PDF):
 *   Page 0 (1): Cover — property address, cooling off notice
 *   Page 1 (2): Signing — purchaser/vendor signatures
 *   Page 2 (3): Table of contents
 *   Page 3 (4): Particulars — estate agent, vendor, vendor solicitor
 *   Page 4 (5): Particulars — purchaser, purchaser solicitor
 *   Page 5 (6): Land details, payment
 *   Page 6 (7): Deposit bond, bank guarantee, GST, settlement, lease
 *   Page 7 (8): Terms contract, loan, building/pest report, special conditions
 */
export const VIC_CONTRACT_OF_SALE_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === PAGE 4 (index 4): Purchaser details ===
  {
    skillFieldId: 'purchaser_name',
    schemaName: 'purchaser_name',
    page: 4,
    position: { x: 52, y: 22 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_address',
    schemaName: 'purchaser_address',
    page: 4,
    position: { x: 52, y: 37 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_phone',
    schemaName: 'purchaser_phone',
    page: 4,
    position: { x: 52, y: 52 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_email',
    schemaName: 'purchaser_email',
    page: 4,
    position: { x: 52, y: 67 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 4 (index 4): Purchaser's solicitor ===
  {
    skillFieldId: 'solicitor_name',
    schemaName: 'solicitor_name',
    page: 4,
    position: { x: 52, y: 95 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_address',
    schemaName: 'solicitor_address',
    page: 4,
    position: { x: 52, y: 110 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_phone',
    schemaName: 'solicitor_phone',
    page: 4,
    position: { x: 52, y: 125 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_fax',
    schemaName: 'solicitor_fax',
    page: 4,
    position: { x: 52, y: 140 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_email',
    schemaName: 'solicitor_email',
    page: 4,
    position: { x: 52, y: 155 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 5 (index 5): Payment ===
  {
    skillFieldId: 'price',
    schemaName: 'price',
    page: 5,
    position: { x: 70, y: 130 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'deposit',
    schemaName: 'deposit',
    page: 5,
    position: { x: 70, y: 145 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'deposit_due_date',
    schemaName: 'deposit_due_date',
    page: 5,
    position: { x: 70, y: 160 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'amount_already_paid',
    schemaName: 'amount_already_paid',
    page: 5,
    position: { x: 70, y: 175 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'balance_at_settlement',
    schemaName: 'balance_at_settlement',
    page: 5,
    position: { x: 70, y: 190 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },

  // === PAGE 6 (index 6): Settlement, GST ===
  {
    skillFieldId: 'settlement_date',
    schemaName: 'settlement_date',
    page: 6,
    position: { x: 70, y: 139 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'gst_farming_business',
    schemaName: 'gst_farming_business',
    page: 6,
    position: { x: 70, y: 93 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'gst_margin_scheme',
    schemaName: 'gst_margin_scheme',
    page: 6,
    position: { x: 70, y: 113 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 7 (index 7): Loan, special conditions ===
  {
    skillFieldId: 'loan_lender',
    schemaName: 'loan_lender',
    page: 7,
    position: { x: 52, y: 78 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'loan_amount',
    schemaName: 'loan_amount',
    page: 7,
    position: { x: 52, y: 93 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'loan_approval_date',
    schemaName: 'loan_approval_date',
    page: 7,
    position: { x: 52, y: 108 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'terms_contract',
    schemaName: 'terms_contract',
    page: 7,
    position: { x: 52, y: 35 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'special_conditions',
    schemaName: 'special_conditions',
    page: 7,
    position: { x: 52, y: 185 },
    width: 130,
    height: 20,
    type: 'text',
    fontSize: 9,
  },

  // === PAGE 1 (index 1): Signing ===
  {
    skillFieldId: 'signing_date',
    schemaName: 'signing_date',
    page: 1,
    position: { x: 82, y: 118 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'print_name',
    schemaName: 'print_name',
    page: 1,
    position: { x: 82, y: 137 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'authority_nature',
    schemaName: 'authority_nature',
    page: 1,
    position: { x: 82, y: 157 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'offer_lapse_days',
    schemaName: 'offer_lapse_days',
    page: 1,
    position: { x: 85, y: 172 },
    width: 15,
    height: 8,
    type: 'text',
    fontSize: 10,
    alignment: 'center',
  },
];

/**
 * Coordinate mappings for Victorian Section 32 Vendor's Statement.
 * Standard REIV/REAC A4 form (210mm x 297mm). Coordinates are placeholder values —
 * calibrate against the real PDF once uploaded.
 *
 * Page layout:
 *   Page 0: Cover/header — vendor details, property address, title details
 *   Page 1: Legal practitioner details, outgoings
 *   Page 2: Mortgage, planning, permits
 *   Page 3: Services, special conditions
 */
export const SECTION_32_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === PAGE 0: Vendor details ===
  {
    skillFieldId: 'vendor_name',
    schemaName: 'vendor_name',
    page: 0,
    position: { x: 70, y: 22 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_address',
    schemaName: 'vendor_address',
    page: 0,
    position: { x: 70, y: 34 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_phone',
    schemaName: 'vendor_phone',
    page: 0,
    position: { x: 70, y: 46 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_email',
    schemaName: 'vendor_email',
    page: 0,
    position: { x: 70, y: 58 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 0: Property & title ===
  {
    skillFieldId: 'property_address',
    schemaName: 'property_address',
    page: 0,
    position: { x: 70, y: 85 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'title_volume',
    schemaName: 'title_volume',
    page: 0,
    position: { x: 70, y: 100 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'title_folio',
    schemaName: 'title_folio',
    page: 0,
    position: { x: 135, y: 100 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'lot_number',
    schemaName: 'lot_number',
    page: 0,
    position: { x: 70, y: 112 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'plan_number',
    schemaName: 'plan_number',
    page: 0,
    position: { x: 135, y: 112 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'title_type',
    schemaName: 'title_type',
    page: 0,
    position: { x: 70, y: 124 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'council_name',
    schemaName: 'council_name',
    page: 0,
    position: { x: 70, y: 136 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 1: Vendor's legal practitioner ===
  {
    skillFieldId: 'vendor_solicitor_name',
    schemaName: 'vendor_solicitor_name',
    page: 1,
    position: { x: 70, y: 22 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_solicitor_firm',
    schemaName: 'vendor_solicitor_firm',
    page: 1,
    position: { x: 70, y: 34 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_solicitor_address',
    schemaName: 'vendor_solicitor_address',
    page: 1,
    position: { x: 70, y: 46 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_solicitor_phone',
    schemaName: 'vendor_solicitor_phone',
    page: 1,
    position: { x: 70, y: 58 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'vendor_solicitor_email',
    schemaName: 'vendor_solicitor_email',
    page: 1,
    position: { x: 70, y: 70 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 1: Outgoings ===
  {
    skillFieldId: 'council_rates',
    schemaName: 'council_rates',
    page: 1,
    position: { x: 70, y: 110 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'water_authority',
    schemaName: 'water_authority',
    page: 1,
    position: { x: 70, y: 122 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'water_rates',
    schemaName: 'water_rates',
    page: 1,
    position: { x: 70, y: 134 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'land_tax',
    schemaName: 'land_tax',
    page: 1,
    position: { x: 70, y: 146 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'owners_corp_fees',
    schemaName: 'owners_corp_fees',
    page: 1,
    position: { x: 70, y: 158 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'other_outgoings',
    schemaName: 'other_outgoings',
    page: 1,
    position: { x: 70, y: 170 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },

  // === PAGE 2: Mortgage ===
  {
    skillFieldId: 'mortgage_holder',
    schemaName: 'mortgage_holder',
    page: 2,
    position: { x: 70, y: 22 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'mortgage_amount',
    schemaName: 'mortgage_amount',
    page: 2,
    position: { x: 70, y: 34 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'mortgage_type',
    schemaName: 'mortgage_type',
    page: 2,
    position: { x: 70, y: 46 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 2: Planning & permits ===
  {
    skillFieldId: 'zoning_code',
    schemaName: 'zoning_code',
    page: 2,
    position: { x: 70, y: 85 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'planning_overlay',
    schemaName: 'planning_overlay',
    page: 2,
    position: { x: 70, y: 97 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'building_permits_7yrs',
    schemaName: 'building_permits_7yrs',
    page: 2,
    position: { x: 70, y: 109 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'permit_details',
    schemaName: 'permit_details',
    page: 2,
    position: { x: 70, y: 121 },
    width: 120,
    height: 20,
    type: 'text',
    fontSize: 9,
  },
  {
    skillFieldId: 'owner_builder',
    schemaName: 'owner_builder',
    page: 2,
    position: { x: 70, y: 145 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },

  // === PAGE 3: Services ===
  {
    skillFieldId: 'service_water',
    schemaName: 'service_water',
    page: 3,
    position: { x: 70, y: 22 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'service_drainage',
    schemaName: 'service_drainage',
    page: 3,
    position: { x: 70, y: 34 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'service_sewerage',
    schemaName: 'service_sewerage',
    page: 3,
    position: { x: 70, y: 46 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'service_electricity',
    schemaName: 'service_electricity',
    page: 3,
    position: { x: 70, y: 58 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'service_gas',
    schemaName: 'service_gas',
    page: 3,
    position: { x: 70, y: 70 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },
  {
    skillFieldId: 'service_telephone',
    schemaName: 'service_telephone',
    page: 3,
    position: { x: 70, y: 82 },
    width: 8,
    height: 8,
    type: 'checkbox',
  },

  // === PAGE 3: Special conditions ===
  {
    skillFieldId: 'chattels_included',
    schemaName: 'chattels_included',
    page: 3,
    position: { x: 20, y: 115 },
    width: 170,
    height: 20,
    type: 'text',
    fontSize: 9,
  },
  {
    skillFieldId: 'special_conditions',
    schemaName: 'special_conditions',
    page: 3,
    position: { x: 20, y: 150 },
    width: 170,
    height: 30,
    type: 'text',
    fontSize: 9,
  },
];

/**
 * Coordinate mappings for Trust Account Reconciliation Report.
 * Single page A4 (210mm x 297mm). Values are right-aligned currency figures.
 * Measured from the report layout:
 *   - Left labels start ~12mm, values right-aligned ending ~195mm
 *   - Header: top 30mm
 *   - Bank Account section: ~48-90mm
 *   - Cash Book: ~100-140mm
 *   - Ledger Balances: ~155-195mm
 *   - Sign off: ~220-260mm
 */
export const RECONCILIATION_REPORT_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === Header ===
  {
    skillFieldId: 'report_date',
    schemaName: 'report_date',
    page: 0,
    position: { x: 12, y: 8 },
    width: 60,
    height: 5,
    type: 'text',
    fontSize: 8,
  },
  {
    skillFieldId: 'trust_account',
    schemaName: 'trust_account',
    page: 0,
    position: { x: 130, y: 8 },
    width: 65,
    height: 5,
    type: 'text',
    fontSize: 8,
    alignment: 'right',
  },
  {
    skillFieldId: 'report_month',
    schemaName: 'report_month',
    page: 0,
    position: { x: 65, y: 28 },
    width: 80,
    height: 6,
    type: 'text',
    fontSize: 10,
    alignment: 'center',
  },

  // === Bank Account Section ===
  {
    skillFieldId: 'bank_balance',
    schemaName: 'bank_balance',
    page: 0,
    position: { x: 155, y: 52 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'unrec_deposits',
    schemaName: 'unrec_deposits',
    page: 0,
    position: { x: 155, y: 58 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'unrec_withdrawals',
    schemaName: 'unrec_withdrawals',
    page: 0,
    position: { x: 155, y: 64 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'adjustments',
    schemaName: 'adjustments',
    page: 0,
    position: { x: 155, y: 70 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'cash_not_banked',
    schemaName: 'cash_not_banked',
    page: 0,
    position: { x: 155, y: 76 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'withdrawals_not_processed',
    schemaName: 'withdrawals_not_processed',
    page: 0,
    position: { x: 155, y: 82 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'reconciled_balance',
    schemaName: 'reconciled_balance',
    page: 0,
    position: { x: 155, y: 90 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Cash Book Section ===
  {
    skillFieldId: 'balance_brought_forward',
    schemaName: 'balance_brought_forward',
    page: 0,
    position: { x: 155, y: 105 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'new_receipts',
    schemaName: 'new_receipts',
    page: 0,
    position: { x: 155, y: 113 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'new_withdrawals',
    schemaName: 'new_withdrawals',
    page: 0,
    position: { x: 155, y: 119 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'cashbook_balance',
    schemaName: 'cashbook_balance',
    page: 0,
    position: { x: 155, y: 127 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Ledger Balances Section ===
  {
    skillFieldId: 'ledger_owner',
    schemaName: 'ledger_owner',
    page: 0,
    position: { x: 155, y: 150 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_supplier',
    schemaName: 'ledger_supplier',
    page: 0,
    position: { x: 155, y: 156 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_tenant',
    schemaName: 'ledger_tenant',
    page: 0,
    position: { x: 155, y: 162 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_total',
    schemaName: 'ledger_total',
    page: 0,
    position: { x: 155, y: 170 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Sign Off ===
  {
    skillFieldId: 'balance_difference',
    schemaName: 'balance_difference',
    page: 0,
    position: { x: 155, y: 192 },
    width: 40,
    height: 6,
    type: 'text',
    fontSize: 10,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'signatory_name',
    schemaName: 'signatory_name',
    page: 0,
    position: { x: 42, y: 244 },
    width: 70,
    height: 6,
    type: 'text',
    fontSize: 10,
  },
];

/**
 * Coordinate mappings for Victorian Transfer of Land.
 * Single-page A4 document (210mm x 297mm). Placeholder coordinates —
 * calibrate against the real PDF once uploaded.
 *
 * Page layout:
 *   Page 0: Title details, transferor, transferee, consideration, encumbrances, execution
 */
export const TRANSFER_OF_LAND_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === Title details ===
  {
    skillFieldId: 'title_volume',
    schemaName: 'title_volume',
    page: 0,
    position: { x: 70, y: 22 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'title_folio',
    schemaName: 'title_folio',
    page: 0,
    position: { x: 135, y: 22 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'lot_number',
    schemaName: 'lot_number',
    page: 0,
    position: { x: 70, y: 34 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'plan_number',
    schemaName: 'plan_number',
    page: 0,
    position: { x: 135, y: 34 },
    width: 55,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'property_address',
    schemaName: 'property_address',
    page: 0,
    position: { x: 70, y: 46 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === Transferor ===
  {
    skillFieldId: 'transferor_name',
    schemaName: 'transferor_name',
    page: 0,
    position: { x: 70, y: 75 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'transferor_address',
    schemaName: 'transferor_address',
    page: 0,
    position: { x: 70, y: 87 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === Transferee ===
  {
    skillFieldId: 'transferee_name',
    schemaName: 'transferee_name',
    page: 0,
    position: { x: 70, y: 116 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'transferee_address',
    schemaName: 'transferee_address',
    page: 0,
    position: { x: 70, y: 128 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'consideration',
    schemaName: 'consideration',
    page: 0,
    position: { x: 70, y: 140 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },

  // === Encumbrances ===
  {
    skillFieldId: 'encumbrance_details',
    schemaName: 'encumbrance_details',
    page: 0,
    position: { x: 20, y: 168 },
    width: 170,
    height: 20,
    type: 'text',
    fontSize: 9,
  },

  // === Execution ===
  {
    skillFieldId: 'execution_date',
    schemaName: 'execution_date',
    page: 0,
    position: { x: 70, y: 210 },
    width: 80,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'witness_name',
    schemaName: 'witness_name',
    page: 0,
    position: { x: 70, y: 240 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'witness_address',
    schemaName: 'witness_address',
    page: 0,
    position: { x: 70, y: 252 },
    width: 120,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
];
