import type { PdfmeFieldMapping } from '@/types/skill';

/**
 * Coordinate mappings for the Victorian Contract of Sale of Land.
 * Measured from the standard REIV form (A4 pages, 210mm x 297mm).
 * All positions are in mm from the top-left corner of the page.
 * Pages are 0-indexed.
 *
 * Page layout (from the PDF):
 *   Page 0 (1): Cover — property address, cooling off notice
 *   Page 1 (2): Signing — purchaser/vendor signatures
 *   Page 2 (3): Table of contents
 *   Page 3 (4): Particulars — estate agent, vendor, vendor solicitor
 *   Page 4 (5): Particulars — purchaser, purchaser solicitor
 *   Page 5 (6): Land details, payment
 *   Page 6 (7): Deposit bond, bank guarantee, GST, settlement, lease
 *   Page 7 (8): Terms contract, loan, building/pest report, special conditions
 */
export const VIC_CONTRACT_OF_SALE_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === PAGE 4 (index 4): Purchaser details ===
  {
    skillFieldId: 'purchaser_name',
    schemaName: 'purchaser_name',
    page: 4,
    position: { x: 52, y: 22 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_address',
    schemaName: 'purchaser_address',
    page: 4,
    position: { x: 52, y: 37 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_phone',
    schemaName: 'purchaser_phone',
    page: 4,
    position: { x: 52, y: 52 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'purchaser_email',
    schemaName: 'purchaser_email',
    page: 4,
    position: { x: 52, y: 67 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 4 (index 4): Purchaser's solicitor ===
  {
    skillFieldId: 'solicitor_name',
    schemaName: 'solicitor_name',
    page: 4,
    position: { x: 52, y: 95 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_address',
    schemaName: 'solicitor_address',
    page: 4,
    position: { x: 52, y: 110 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_phone',
    schemaName: 'solicitor_phone',
    page: 4,
    position: { x: 52, y: 125 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_fax',
    schemaName: 'solicitor_fax',
    page: 4,
    position: { x: 52, y: 140 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'solicitor_email',
    schemaName: 'solicitor_email',
    page: 4,
    position: { x: 52, y: 155 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 5 (index 5): Payment ===
  {
    skillFieldId: 'price',
    schemaName: 'price',
    page: 5,
    position: { x: 70, y: 130 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'deposit',
    schemaName: 'deposit',
    page: 5,
    position: { x: 70, y: 145 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'deposit_due_date',
    schemaName: 'deposit_due_date',
    page: 5,
    position: { x: 70, y: 160 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'amount_already_paid',
    schemaName: 'amount_already_paid',
    page: 5,
    position: { x: 70, y: 175 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'balance_at_settlement',
    schemaName: 'balance_at_settlement',
    page: 5,
    position: { x: 70, y: 190 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },

  // === PAGE 6 (index 6): Settlement, GST ===
  {
    skillFieldId: 'settlement_date',
    schemaName: 'settlement_date',
    page: 6,
    position: { x: 70, y: 139 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'gst_farming_business',
    schemaName: 'gst_farming_business',
    page: 6,
    position: { x: 70, y: 93 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'gst_margin_scheme',
    schemaName: 'gst_margin_scheme',
    page: 6,
    position: { x: 70, y: 113 },
    width: 110,
    height: 8,
    type: 'text',
    fontSize: 10,
  },

  // === PAGE 7 (index 7): Loan, special conditions ===
  {
    skillFieldId: 'loan_lender',
    schemaName: 'loan_lender',
    page: 7,
    position: { x: 52, y: 78 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'loan_amount',
    schemaName: 'loan_amount',
    page: 7,
    position: { x: 52, y: 93 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
    transform: 'currency_au',
  },
  {
    skillFieldId: 'loan_approval_date',
    schemaName: 'loan_approval_date',
    page: 7,
    position: { x: 52, y: 108 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'terms_contract',
    schemaName: 'terms_contract',
    page: 7,
    position: { x: 52, y: 35 },
    width: 130,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'special_conditions',
    schemaName: 'special_conditions',
    page: 7,
    position: { x: 52, y: 185 },
    width: 130,
    height: 20,
    type: 'text',
    fontSize: 9,
  },

  // === PAGE 1 (index 1): Signing ===
  {
    skillFieldId: 'signing_date',
    schemaName: 'signing_date',
    page: 1,
    position: { x: 82, y: 118 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'print_name',
    schemaName: 'print_name',
    page: 1,
    position: { x: 82, y: 137 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'authority_nature',
    schemaName: 'authority_nature',
    page: 1,
    position: { x: 82, y: 157 },
    width: 100,
    height: 8,
    type: 'text',
    fontSize: 10,
  },
  {
    skillFieldId: 'offer_lapse_days',
    schemaName: 'offer_lapse_days',
    page: 1,
    position: { x: 85, y: 172 },
    width: 15,
    height: 8,
    type: 'text',
    fontSize: 10,
    alignment: 'center',
  },
];

/**
 * Coordinate mappings for Trust Account Reconciliation Report.
 * Single page A4 (210mm x 297mm). Values are right-aligned currency figures.
 * Measured from the report layout:
 *   - Left labels start ~12mm, values right-aligned ending ~195mm
 *   - Header: top 30mm
 *   - Bank Account section: ~48-90mm
 *   - Cash Book: ~100-140mm
 *   - Ledger Balances: ~155-195mm
 *   - Sign off: ~220-260mm
 */
export const RECONCILIATION_REPORT_PDFME_MAPPINGS: PdfmeFieldMapping[] = [
  // === Header ===
  {
    skillFieldId: 'report_date',
    schemaName: 'report_date',
    page: 0,
    position: { x: 12, y: 8 },
    width: 60,
    height: 5,
    type: 'text',
    fontSize: 8,
  },
  {
    skillFieldId: 'trust_account',
    schemaName: 'trust_account',
    page: 0,
    position: { x: 130, y: 8 },
    width: 65,
    height: 5,
    type: 'text',
    fontSize: 8,
    alignment: 'right',
  },
  {
    skillFieldId: 'report_month',
    schemaName: 'report_month',
    page: 0,
    position: { x: 65, y: 28 },
    width: 80,
    height: 6,
    type: 'text',
    fontSize: 10,
    alignment: 'center',
  },

  // === Bank Account Section ===
  {
    skillFieldId: 'bank_balance',
    schemaName: 'bank_balance',
    page: 0,
    position: { x: 155, y: 52 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'unrec_deposits',
    schemaName: 'unrec_deposits',
    page: 0,
    position: { x: 155, y: 58 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'unrec_withdrawals',
    schemaName: 'unrec_withdrawals',
    page: 0,
    position: { x: 155, y: 64 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'adjustments',
    schemaName: 'adjustments',
    page: 0,
    position: { x: 155, y: 70 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'cash_not_banked',
    schemaName: 'cash_not_banked',
    page: 0,
    position: { x: 155, y: 76 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'withdrawals_not_processed',
    schemaName: 'withdrawals_not_processed',
    page: 0,
    position: { x: 155, y: 82 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'reconciled_balance',
    schemaName: 'reconciled_balance',
    page: 0,
    position: { x: 155, y: 90 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Cash Book Section ===
  {
    skillFieldId: 'balance_brought_forward',
    schemaName: 'balance_brought_forward',
    page: 0,
    position: { x: 155, y: 105 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'new_receipts',
    schemaName: 'new_receipts',
    page: 0,
    position: { x: 155, y: 113 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'new_withdrawals',
    schemaName: 'new_withdrawals',
    page: 0,
    position: { x: 155, y: 119 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'cashbook_balance',
    schemaName: 'cashbook_balance',
    page: 0,
    position: { x: 155, y: 127 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Ledger Balances Section ===
  {
    skillFieldId: 'ledger_owner',
    schemaName: 'ledger_owner',
    page: 0,
    position: { x: 155, y: 150 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_supplier',
    schemaName: 'ledger_supplier',
    page: 0,
    position: { x: 155, y: 156 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_tenant',
    schemaName: 'ledger_tenant',
    page: 0,
    position: { x: 155, y: 162 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'ledger_total',
    schemaName: 'ledger_total',
    page: 0,
    position: { x: 155, y: 170 },
    width: 40,
    height: 5,
    type: 'text',
    fontSize: 9,
    alignment: 'right',
    transform: 'currency_au',
  },

  // === Sign Off ===
  {
    skillFieldId: 'balance_difference',
    schemaName: 'balance_difference',
    page: 0,
    position: { x: 155, y: 192 },
    width: 40,
    height: 6,
    type: 'text',
    fontSize: 10,
    alignment: 'right',
    transform: 'currency_au',
  },
  {
    skillFieldId: 'signatory_name',
    schemaName: 'signatory_name',
    page: 0,
    position: { x: 42, y: 244 },
    width: 70,
    height: 6,
    type: 'text',
    fontSize: 10,
  },
];
