import type { SkillDefinition } from '@/types/skill';
import { VIC_CONTRACT_OF_SALE_PDFME_MAPPINGS } from '@/lib/pdf/pdfmeTemplates';

export const vicContractOfSaleOffer: SkillDefinition = {
  id: 'vic_contract_of_sale_offer',
  name: 'Contract of Sale Offer',
  description:
    'Fill out the purchaser side of a Victorian Contract of Sale of Land. Covers purchaser details, solicitor, payment, conditions, and signing.',
  icon: 'FileSignature',
  version: '1.0',
  jurisdiction: 'VIC, Australia',
  documentType: 'Contract of Sale of Land',

  sections: [
    {
      id: 'purchaser_details',
      title: 'Purchaser Details',
      description: 'Your personal or company details as the purchaser.',
      fields: [
        {
          id: 'purchaser_name',
          label: 'Purchaser Name(s)',
          type: 'text',
          placeholder: 'e.g. Jane Smith & John Smith',
          required: true,
          profileKey: 'full_name',
          helpText: 'Full legal name(s) of all purchasers.',
        },
        {
          id: 'purchaser_address',
          label: 'Address',
          type: 'text',
          placeholder: 'e.g. 10 Collins Street, Melbourne VIC 3000',
          required: true,
          profileKey: 'address_line_1',
        },
        {
          id: 'purchaser_phone',
          label: 'Telephone',
          type: 'phone',
          placeholder: 'e.g. 0412 345 678',
          profileKey: 'phone',
        },
        {
          id: 'purchaser_email',
          label: 'Email',
          type: 'email',
          placeholder: 'e.g. jane@example.com',
          profileKey: 'email',
          validation: {
            pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
            patternMessage: 'Please enter a valid email address.',
          },
        },
      ],
    },
    {
      id: 'purchaser_solicitor',
      title: "Purchaser's Legal Practitioner",
      description: 'Details of your solicitor or conveyancer.',
      fields: [
        {
          id: 'solicitor_name',
          label: 'Name',
          type: 'text',
          placeholder: 'e.g. Smith & Partners Conveyancing',
        },
        {
          id: 'solicitor_address',
          label: 'Address',
          type: 'text',
          placeholder: 'e.g. 1 Queen Street, Melbourne VIC 3000',
        },
        {
          id: 'solicitor_phone',
          label: 'Telephone',
          type: 'phone',
          placeholder: 'e.g. 03 9123 4567',
        },
        {
          id: 'solicitor_fax',
          label: 'Fax',
          type: 'phone',
          placeholder: 'Optional',
        },
        {
          id: 'solicitor_email',
          label: 'Email',
          type: 'email',
          placeholder: 'e.g. info@smithconveyancing.com.au',
        },
      ],
    },
    {
      id: 'payment',
      title: 'Payment',
      description: 'Purchase price, deposit, and settlement payment details.',
      fields: [
        {
          id: 'price',
          label: 'Price',
          type: 'currency',
          placeholder: 'e.g. 750000',
          required: true,
          helpText: 'The total purchase price in AUD.',
        },
        {
          id: 'deposit',
          label: 'Deposit',
          type: 'currency',
          placeholder: 'e.g. 75000',
          required: true,
          helpText: 'Usually 10% of the purchase price.',
        },
        {
          id: 'deposit_due_date',
          label: 'Deposit Due By',
          type: 'date',
          placeholder: 'dd/mm/yyyy',
          required: true,
        },
        {
          id: 'amount_already_paid',
          label: 'Amount Already Paid',
          type: 'currency',
          placeholder: 'e.g. 1000',
          helpText: 'Any amount already paid toward the deposit.',
        },
        {
          id: 'balance_at_settlement',
          label: 'Balance Payable at Settlement',
          type: 'currency',
          computed: true,
          helpText: 'Automatically calculated: Price minus Deposit.',
        },
      ],
    },
    {
      id: 'conditions',
      title: 'Conditions & Options',
      description: 'Settlement, finance, inspections, and special conditions.',
      fields: [
        {
          id: 'settlement_date',
          label: 'Settlement Date',
          type: 'date',
          placeholder: 'dd/mm/yyyy',
          required: true,
          helpText: 'The date settlement is due.',
        },
        {
          id: 'deposit_bond',
          label: 'Deposit Bond',
          type: 'checkbox',
          helpText: 'Check if a deposit bond will be used instead of cash deposit.',
        },
        {
          id: 'bank_guarantee',
          label: 'Bank Guarantee',
          type: 'checkbox',
          helpText: 'Check if a bank guarantee will be provided.',
        },
        {
          id: 'gst_plus_gst',
          label: 'Price is Plus GST',
          type: 'checkbox',
          helpText: 'Check if GST is payable in addition to the price.',
        },
        {
          id: 'gst_farming_business',
          label: 'Farming Business / Going Concern',
          type: 'text',
          placeholder: 'e.g. farming business',
          helpText: "Enter 'farming business' or 'going concern' if applicable.",
        },
        {
          id: 'gst_margin_scheme',
          label: 'Margin Scheme',
          type: 'text',
          placeholder: 'e.g. margin scheme',
          helpText: "Enter 'margin scheme' if the margin scheme applies.",
        },
        {
          id: 'loan_lender',
          label: 'Loan — Lender',
          type: 'text',
          placeholder: 'e.g. Commonwealth Bank',
          helpText: 'Leave blank if not subject to finance.',
        },
        {
          id: 'loan_amount',
          label: 'Loan — Amount',
          type: 'currency',
          placeholder: 'e.g. 600000',
        },
        {
          id: 'loan_approval_date',
          label: 'Loan — Approval Date',
          type: 'date',
          placeholder: 'dd/mm/yyyy',
          helpText: 'Date by which finance must be approved.',
        },
        {
          id: 'building_report',
          label: 'Building Report',
          type: 'checkbox',
          helpText: 'Check to make the contract subject to a satisfactory building report.',
        },
        {
          id: 'pest_report',
          label: 'Pest Report',
          type: 'checkbox',
          helpText: 'Check to make the contract subject to a satisfactory pest report.',
        },
        {
          id: 'terms_contract',
          label: 'Terms Contract',
          type: 'text',
          placeholder: "Enter 'terms contract' if applicable",
          helpText: 'Only if this is a terms contract under the Sale of Land Act 1962.',
        },
        {
          id: 'special_conditions',
          label: 'Special Conditions',
          type: 'textarea',
          placeholder: 'Enter any additional special conditions...',
          helpText: 'Additional conditions to be added to the contract.',
        },
      ],
    },
    {
      id: 'signing',
      title: 'Signing',
      description: 'Details for signing the contract as purchaser.',
      fields: [
        {
          id: 'signing_date',
          label: 'Date of Signing',
          type: 'date',
          placeholder: 'dd/mm/yyyy',
          required: true,
        },
        {
          id: 'print_name',
          label: 'Print Name(s) of Person(s) Signing',
          type: 'text',
          placeholder: 'e.g. Jane Smith',
          required: true,
          profileKey: 'full_name',
        },
        {
          id: 'authority_nature',
          label: 'Nature of Authority (if applicable)',
          type: 'text',
          placeholder: "e.g. 'director', 'attorney under power of attorney'",
          helpText: 'Leave blank if signing as the purchaser personally.',
        },
        {
          id: 'offer_lapse_days',
          label: 'Offer Lapse Period (business days)',
          type: 'text',
          placeholder: 'e.g. 3',
          helpText: 'Number of clear business days before the offer lapses. Default is 3 if blank.',
          validation: {
            pattern: '^\\d*$',
            patternMessage: 'Please enter a number.',
          },
        },
      ],
    },
  ],

  fieldMappings: [
    // Purchaser details
    { skillFieldId: 'purchaser_name', pdfFieldName: 'Purchaser Names' },
    { skillFieldId: 'purchaser_address', pdfFieldName: 'Purchaser Address' },
    { skillFieldId: 'purchaser_phone', pdfFieldName: 'Purchaser Telephone' },
    { skillFieldId: 'purchaser_email', pdfFieldName: 'Purchaser Email' },
    // Purchaser solicitor
    { skillFieldId: 'solicitor_name', pdfFieldName: 'Purchaser Solicitor Name' },
    { skillFieldId: 'solicitor_address', pdfFieldName: 'Purchaser Solicitor Address' },
    { skillFieldId: 'solicitor_phone', pdfFieldName: 'Purchaser Solicitor Telephone' },
    { skillFieldId: 'solicitor_fax', pdfFieldName: 'Purchaser Solicitor Fax' },
    { skillFieldId: 'solicitor_email', pdfFieldName: 'Purchaser Solicitor Email' },
    // Payment
    { skillFieldId: 'price', pdfFieldName: 'Price', transform: 'currency_au' },
    { skillFieldId: 'deposit', pdfFieldName: 'Deposit', transform: 'currency_au' },
    { skillFieldId: 'deposit_due_date', pdfFieldName: 'Deposit Due Date', transform: 'date_au' },
    { skillFieldId: 'amount_already_paid', pdfFieldName: 'Amount Paid', transform: 'currency_au' },
    { skillFieldId: 'balance_at_settlement', pdfFieldName: 'Balance at Settlement', transform: 'currency_au' },
    // Conditions
    { skillFieldId: 'settlement_date', pdfFieldName: 'Settlement Date', transform: 'date_au' },
    { skillFieldId: 'deposit_bond', pdfFieldName: 'Deposit Bond Checkbox' },
    { skillFieldId: 'bank_guarantee', pdfFieldName: 'Bank Guarantee Checkbox' },
    { skillFieldId: 'gst_plus_gst', pdfFieldName: 'GST Plus GST' },
    { skillFieldId: 'gst_farming_business', pdfFieldName: 'GST Farming Business' },
    { skillFieldId: 'gst_margin_scheme', pdfFieldName: 'GST Margin Scheme' },
    { skillFieldId: 'loan_lender', pdfFieldName: 'Loan Lender' },
    { skillFieldId: 'loan_amount', pdfFieldName: 'Loan Amount', transform: 'currency_au' },
    { skillFieldId: 'loan_approval_date', pdfFieldName: 'Loan Approval Date', transform: 'date_au' },
    { skillFieldId: 'building_report', pdfFieldName: 'Building Report Checkbox' },
    { skillFieldId: 'pest_report', pdfFieldName: 'Pest Report Checkbox' },
    { skillFieldId: 'terms_contract', pdfFieldName: 'Terms Contract' },
    { skillFieldId: 'special_conditions', pdfFieldName: 'Special Conditions Text' },
    // Signing
    { skillFieldId: 'signing_date', pdfFieldName: 'Purchaser Signing Date', transform: 'date_au' },
    { skillFieldId: 'print_name', pdfFieldName: 'Purchaser Print Name' },
    { skillFieldId: 'authority_nature', pdfFieldName: 'Purchaser Authority' },
    { skillFieldId: 'offer_lapse_days', pdfFieldName: 'Offer Lapse Days' },
  ],

  computedFields: [
    {
      skillFieldId: 'balance_at_settlement',
      formula: 'subtract',
      operands: ['price', 'deposit'],
      pdfFieldName: 'Balance at Settlement',
    },
  ],

  pdfmeFieldMappings: VIC_CONTRACT_OF_SALE_PDFME_MAPPINGS,
};
